M48
; DRILL file {KiCad 9.0.2-9.0.2-0~ubuntu24.04.1} date 2025-06-13T17:41:29-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-13T17:41:29-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2-9.0.2-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X180.735Y-106.965
X180.735Y-112.735
M30
