M48
; DRILL file {KiCad 9.0.5-9.0.5~ubuntu24.04.1} date 2025-10-12T15:53:46-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-12T15:53:46-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5-9.0.5~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X180.735Y-106.965
X180.735Y-112.735
M30
